apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c --volumes hostPath
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: free5gc-upf-1
  name: free5gc-upf-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: free5gc-upf-1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/privnet: "true"
        io.kompose.service: free5gc-upf-1
    spec:
      containers:
        - args:
            - ./free5gc-upfd
            - -f
            - /free5gc/config/upfcfg.yaml
          image: lttp94/f5gc-upf-1
          name: upf1
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /free5gc/config/upfcfg.yaml
              name: upf1-config-map-volume
              subPath: upfcfg1.yaml
      restartPolicy: Always
      volumes:
        - name: upf1-config-map-volume
          configMap:
            name: upf1-config-map
status: {}
