apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c --volumes hostPath
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: free5gc-upf-1
  name: free5gc-upf-1
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: free5gc-upf-1
status:
  loadBalancer: {}
