name: docker-compose
description: A generated Helm Chart for docker-compose from Skippbox Kompose
version: 0.0.1
apiVersion: v1
keywords:
  - docker-compose
sources:
home:
dependencies:
  - name: mongodb
    version: 0.1.0
  - name: amf
    version: 0.1.0
  - name: nrf
    version: 0.1.0
