# Default values for free5gcservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#192.168.26.11
createNamespace: false
namespace: free5gc
mongodb:
  enabled: true
  controller:
    replicaCount: 1
    cpu: 200m
    image:
      tag: 4.1.1-xenial
    pvc:
      volumeType: nfs
      nfsPath: /nfsshare/mongodb
      nfsServer: 172.29.120.85
      reclaimPolicy: Recycle
      accessModes: ReadWriteMany
      storageClass: mongo
      storage: 10Gi
  service:
    nodePort: true
    nodePortNum: 31717

webui:
  enabled: true
  controller:
    replicaCount: 1
    image:
      repository: dockerfree5gc/free5gc-webui
      tag: latest
      pullPolicy: IfNotPresent
  service:
    nodePort: true
    nodePortNum: 31727

free5gc:
  image:
    - repository1: dockerfree5gc/free5gc-amf
      tag1: latest
      pullPolicy1: IfNotPresent
    - repository2: dockerfree5gc/free5gc-hss
      tag2: latest
      pullPolicy2: IfNotPresent
    - repository3: dockerfree5gc/free5gc-smf
      tag3: latest
      pullPolicy3: IfNotPresent
    - repository4: dockerfree5gc/free5gc-pcf
      tag4: latest
      pullPolicy4: IfNotPresent
    - repository5: dockerfree5gc/free5gc-upf
      tag5: latest
      pullPolicy5: IfNotPresent  
  amf:
    enabled: true
    addr: 10.233.100.202
    s1ap: 192.188.2.100
    mcc: 208
    mnc: 93
  hss:
    enabled: true
    addr: 10.233.100.203
  smf:
    enabled: true
    addr: 10.233.100.204
    nodePort: 31780
  pcrf:
    enabled: true
    addr: 10.233.100.205
  upf:
    enabled: true
    addr: 10.233.100.206
    gtpu: 192.188.2.101
