apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c --volumes hostPath
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: free5gc-nssf
  name: free5gc-nssf
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: free5gc-nssf
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/privnet: "true"
        io.kompose.service: free5gc-nssf
    spec:
      containers:
        - args:
            - ./nssf
            - -nssfcfg
            - ../config/nssfcfg.yaml
          env:
            - name: GIN_MODE
              value: release
          image: lttp94/f5gc-nssf:latest
          name: nssf
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /free5gc/config/nssfcfg.yaml
              name: nssf-config-map-volume
              subPath: nssfcfg.yaml
      restartPolicy: Always
      volumes:
        - name: nssf-config-map-volume
          configMap:
            name: nssf-config-map
status: {}
