apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c --volumes hostPath
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: free5gc-smf
  name: free5gc-smf
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: free5gc-smf
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/privnet: "true"
        io.kompose.service: free5gc-smf
    spec:
      containers:
        - args:
            - ./smf
            - -smfcfg
            - ../config/smfcfg.yaml
            - -uerouting
            - ../config/uerouting.yaml
          env:
            - name: GIN_MODE
              value: release
          image: lttp94/f5gc-smf:latest
          name: smf
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /free5gc/config/smfcfg.yaml
              name: smf-config-map-volume
              subPath: smfcfg.yaml
            - mountPath: /free5gc/config/uerouting.yaml
              name: uerouting-config-map-volume
              subPath: uerouting.yaml
      restartPolicy: Always
      volumes:
        - name: smf-config-map-volume
          configMap:
             name: smf-config-map
        - name: uerouting-config-map-volume
          configMap:
            name: uerouting-config-map 
status: {}
