apiVersion: v1
kind: ConfigMap
metadata:
  name: smf-config-map
data:
  smfcfg.yaml: |
    info:
      version: 1.0.0
      description: SMF initial local configuration

    configuration:
      smfName: SMF # the name of this SMF
      sbi: # Service-based interface information
        scheme: http # the protocol for sbi (http or https)
        registerIPv4: free5gc-smf # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: 8000 # Port used to bind the service
        tls: # the local path of TLS key
          key: free5gc/support/TLS/smf.key # SMF TLS Certificate
          pem: free5gc/support/TLS/smf.pem # SMF TLS Private key
      serviceNameList: # the SBI services provided by this SMF, refer to TS 29.502
        - nsmf-pdusession # Nsmf_PDUSession service
        - nsmf-event-exposure # Nsmf_EventExposure service
        - nsmf-oam # OAM service
      snssaiInfos: # the S-NSSAI (Single Network Slice Selection Assistance Information) list supported by this AMF
        - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
            sst: 1 # Slice/Service Type (uinteger, range: 0~255)
            sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
          dnnInfos: # DNN information list
            - dnn: internet # Data Network Name
              dns: # the IP address of DNS
                ipv4: 8.8.8.8
                ipv6: 2001:4860:4860::8888
              ueSubnet: 60.60.0.0/16 # should be CIDR type
        - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
            sst: 1 # Slice/Service Type (uinteger, range: 0~255)
            sd: 112233 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
          dnnInfos: # DNN information list
            - dnn: internet # Data Network Name
              dns: # the IP address of DNS
                ipv4: 8.8.8.8
                ipv6: 2001:4860:4860::8888
              ueSubnet: 10.10.0.0/16 # should be CIDR type
      pfcp: # the IP address of N4 interface on this SMF (PFCP)
        addr: 0.0.0.0
      ulcl: true
      userplane_information: # list of userplane information
        up_nodes: # information of userplane node (AN or UPF)
          gNB1: # the name of the node
            type: AN # the type of the node (AN or UPF)
          BranchingUPF:  # the name of the node
            type: UPF # the type of the node (AN or UPF)
            node_id: free5gc-upfb # the IP/FQDN of N4 interface on this UPF (PFCP)
            sNssaiUpfInfos: # S-NSSAI information list for this UPF
              - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
                  sst: 1 # Slice/Service Type (uinteger, range: 0~255)
                  sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
                dnnUpfInfoList: # DNN information list for this S-NSSAI
                  - dnn: internet
              - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
                  sst: 1 # Slice/Service Type (uinteger, range: 0~255)
                  sd: 112233 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
                dnnUpfInfoList: # DNN information list for this S-NSSAI
                  - dnn: internet
            interfaces: # Interface list for this UPF
              - interfaceType: N3 # the type of the interface (N3 or N9)
                endpoints: # the IP address of this N3/N9 interface on this UPF
                  - free5gc-upf-b
                networkInstance: internet # Data Network Name (DNN)
              - interfaceType: N9 # the type of the interface (N3 or N9)
                endpoints: # the IP address of this N3/N9 interface on this UPF
                  - free5gc-upf-b
                networkInstance: internet # Data Network Name (DNN)
          AnchorUPF1:  # the name of the node
            type: UPF # the type of the node (AN or UPF)
            node_id: free5gc-upf-1 # the IP/FQDN of N4 interface on this UPF (PFCP)
            sNssaiUpfInfos: # S-NSSAI information list for this UPF
              - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
                  sst: 1 # Slice/Service Type (uinteger, range: 0~255)
                  sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
                dnnUpfInfoList: # DNN information list for this S-NSSAI
                  - dnn: internet
              - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
                  sst: 1 # Slice/Service Type (uinteger, range: 0~255)
                  sd: 112233 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
                dnnUpfInfoList: # DNN information list for this S-NSSAI
                  - dnn: internet
            interfaces: # Interface list for this UPF
              - interfaceType: N3 # the type of the interface (N3 or N9)
                endpoints: # the IP address of this N3/N9 interface on this UPF
                  - free5gc-upf-1
                networkInstance: internet # Data Network Name (DNN)
              - interfaceType: N9 # the type of the interface (N3 or N9)
                endpoints: # the IP address of this N3/N9 interface on this UPF
                  - free5gc-upf-1
                networkInstance: internet # Data Network Name (DNN)
          AnchorUPF2:  # the name of the node
            type: UPF # the type of the node (AN or UPF)
            node_id: free5gc-upf-2 # the IP/FQDN of N4 interface on this UPF (PFCP)
            sNssaiUpfInfos: # S-NSSAI information list for this UPF
              - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
                  sst: 1 # Slice/Service Type (uinteger, range: 0~255)
                  sd: 010203 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
                dnnUpfInfoList: # DNN information list for this S-NSSAI
                  - dnn: internet
              - sNssai: # S-NSSAI (Single Network Slice Selection Assistance Information)
                  sst: 1 # Slice/Service Type (uinteger, range: 0~255)
                  sd: 112233 # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
                dnnUpfInfoList: # DNN information list for this S-NSSAI
                  - dnn: internet
            interfaces: # Interface list for this UPF
              - interfaceType: N3 # the type of the interface (N3 or N9)
                endpoints: # the IP address of this N3/N9 interface on this UPF
                  - free5gc-upf-2
                networkInstance: internet # Data Network Name (DNN)
              - interfaceType: N9 # the type of the interface (N3 or N9)
                endpoints: # the IP address of this N3/N9 interface on this UPF
                  - free5gc-upf-2
                networkInstance: internet # Data Network Name (DNN)
        links: # the topology graph of userplane, A and B represent the two nodes of each link
          - A: gNB1
            B: BranchingUPF
          - A: BranchingUPF
            B: AnchorUPF1
          - A: BranchingUPF
            B: AnchorUPF2
      dnn:
        internet:
          dns:
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
        internet2:
          dns:
            ipv4: 8.8.4.4
            ipv6: 2001:4860:4860::8844
      ue_subnet: 60.60.0.0/16
      nrfUri: http://free5gc-nrf:8000 # a valid URI of NRF

    # the kind of log output
      # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: enable the caller report or not, value: true or false
    logger:
      SMF:
        debugLevel: info
        ReportCaller: false
      NAS:
        debugLevel: info
        ReportCaller: false
      NGAP:
        debugLevel: info
        ReportCaller: false
      Aper:
        debugLevel: info
        ReportCaller: false
      PathUtil:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: info
        ReportCaller: false
      PFCP:
        debugLevel: info
        ReportCaller: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: uerouting-config-map
data:
  uerouting.yaml: |
    info:
      version: 1.0.0
      description: Routing information for UE

    ueRoutingInfo: # the list of UE routing information
      - SUPI: imsi-2089300007487 # Subscription Permanent Identifier of the UE
        AN: 10.200.200.101 # the IP address of RAN
        PathList: # the pre-config paths for this SUPI
          - DestinationIP: 60.60.0.100 # the destination IP address on Data Network (DN)
            # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
            # The UPF's name should be consistent with smfcfg.yaml
            UPF: !!seq
              - BranchingUPF
              - AnchorUPF1

          - DestinationIP: 60.60.0.101 # the destination IP address on Data Network (DN)
            # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
            # The UPF's name should be consistent with smfcfg.yaml
            UPF: !!seq
              - BranchingUPF
              - AnchorUPF2

      - SUPI: imsi-2089300007486 # Subscription Permanent Identifier of the UE
        AN: 10.200.200.102 # the IP address of RAN
        PathList: # the pre-config paths for this SUPI
          - DestinationIP: 10.10.0.10 # the destination IP address on Data Network (DN)
            # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
            # The UPF's name should be consistent with smfcfg.yaml
            UPF: !!seq
              - BranchingUPF
              - AnchorUPF1

          - DestinationIP: 10.10.0.11 # the destination IP address on Data Network (DN)
            # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
            # The UPF's name should be consistent with smfcfg.yaml
            UPF: !!seq
              - BranchingUPF
              - AnchorUPF2
