apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c --volumes hostPath
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: free5gc-udr
  name: free5gc-udr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: free5gc-udr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/privnet: "true"
        io.kompose.service: free5gc-udr
    spec:
      containers:
        - args:
            - ./udr
            - -udrcfg
            - ../config/udrcfg.yaml
          env:
            - name: DB_URI
              value: mongodb://db/free5gc
            - name: GIN_MODE
              value: release
          image: lttp94/f5gc-udr:latest
          name: udr
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /free5gc/config/udrcfg.yaml
              name: udr-config-map-volume
              subPath: udrcfg.yaml
      restartPolicy: Always
      volumes:
        - name: udr-config-map-volume
          configMap:
            name: udr-config-map          
status: {}
